#!/usr/bin/env bash
# Canonical commit-message check for every repository in the visionEAE organisation.
# Copied verbatim into <repo>/.lefthook/commit-msg/check-message.sh by bootstrap-repo.sh and run
# by lefthook on every commit. Change the rule here first, then re-seed the repositories.
#
# Usage: check-commit-message.sh <file-with-message>
#        printf '%s' "$message" | check-commit-message.sh -
set -euo pipefail

TYPES='feat|fix|refactor|test|docs|build|ci|chore|perf|style|revert'
PATTERN="^(${TYPES})(\([a-z0-9-]+\))?!?: [a-z0-9].{0,71}$"

if [ "${1:-}" = "-" ]; then message="$(cat)"; else message="$(cat "$1")"; fi
message="$(printf '%s\n' "$message" | grep -v '^#' || true)"
summary="$(printf '%s\n' "$message" | head -n 1)"

# Merge and revert commits generated by git/GitHub are exempt.
case "$summary" in "Merge "*|"Revert \""*) exit 0 ;; esac

if ! printf '%s' "$summary" | grep -Eq "$PATTERN"; then
  cat >&2 <<MSG
✖ Commit message does not follow the visionEAE convention.

  got:      $summary
  expected: <type>(<optional-scope>): <summary>

  type    ∈ { ${TYPES//|/, } }
  scope   : optional, lowercase kebab-case (api, domain, db, security, deps, ...)
  summary : imperative mood, starts lowercase, no trailing period, ≤ 72 chars

  example : feat(security): add refresh token rotation
See CONTRIBUTING.md.
MSG
  exit 1
fi
if printf '%s' "$summary" | grep -Eq '\.$'; then
  echo "✖ Summary must not end with a period." >&2; exit 1
fi
if [ -n "$(printf '%s\n' "$message" | sed -n '2p')" ]; then
  echo "✖ Leave one blank line between the summary and the body." >&2; exit 1
fi
